/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contact
         * @description "Don't have a printer?": send one email to the site owner (decision D19).
         */
        post: operations["contact_api_contact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export
         * @description Full-quality print file. Warnings ride along in ``X-Coin-Warnings``.
         */
        post: operations["export_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filaments */
        get: operations["filaments_api_filaments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filaments/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Filaments Version */
        get: operations["filaments_version_api_filaments_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fonts
         * @description Built-in fonts; ``woff2_url`` is what the SPA loads for the 2D preview.
         */
        get: operations["fonts_api_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fonts/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect Font
         * @description Validate and describe a font upload; the client embeds it in the config itself.
         */
        post: operations["inspect_font_api_fonts_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fonts/{key}.woff2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Font File */
        get: operations["font_file_api_fonts__key__woff2_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: at least one font loads and the filament registry has entries.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process answers HTTP.
         */
        get: operations["healthz_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/icons/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trace
         * @description Trace an uploaded PNG, JPEG or SVG into icon geometry. Stateless: nothing is stored.
         */
        post: operations["trace_api_icons_trace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/glb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Glb
         * @description The coin as GLB with three PBR materials. ``ETag`` is the full config hash.
         */
        post: operations["preview_glb_api_preview_glb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preview/svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Svg
         * @description The authoritative 2D render of one face.
         */
        post: operations["preview_svg_api_preview_svg_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/coin-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coin Config Schema
         * @description JSON Schema of the current ``CoinConfig`` version.
         */
        get: operations["coin_config_schema_api_schema_coin_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stats
         * @description Size, filament grams per material and the filament swap heights.
         */
        post: operations["stats_api_stats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Templates */
        get: operations["templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Check a design. Returns the normalised config and printability warnings.
         */
        post: operations["validate_api_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_inspect_font_api_fonts_inspect_post */
        Body_inspect_font_api_fonts_inspect_post: {
            /** File */
            file: string;
        };
        /** Body_trace_api_icons_trace_post */
        Body_trace_api_icons_trace_post: {
            /** File */
            file: string;
            /**
             * Options
             * @description JSON TraceOptions
             */
            options?: string | null;
        };
        /** CoinConfig */
        CoinConfig: {
            colors?: components["schemas"]["Colors"];
            edge?: components["schemas"]["Edge"];
            faces?: components["schemas"]["Faces"];
            font?: components["schemas"]["FontRef"];
            meta?: components["schemas"]["Meta"];
            print?: components["schemas"]["PrintSettings"];
            rings?: components["schemas"]["Rings"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            size?: components["schemas"]["Size"];
        };
        /**
         * ColorRef
         * @description Either a registry ``filament`` id or a literal ``hex`` colour, never both.
         */
        ColorRef: {
            /** Filament */
            filament?: string | null;
            /** Hex */
            hex?: string | null;
        };
        /** Colors */
        Colors: {
            relief?: components["schemas"]["ColorRef"];
        };
        /** ConfigBody */
        ConfigBody: {
            config: components["schemas"]["CoinConfig"];
        };
        /** ContactRequest */
        ContactRequest: {
            /**
             * Attach Design
             * @default false
             */
            attach_design: boolean;
            config?: components["schemas"]["CoinConfig"] | null;
            /**
             * Elapsed S
             * @description Seconds the form was open, measured by the browser. A duration, not a timestamp, so a visitor's clock being off does not matter.
             */
            elapsed_s: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Honeypot
             * @default
             */
            honeypot: string;
            /**
             * Message
             * @default
             */
            message: string;
            /** Name */
            name: string;
        };
        /**
         * CustomFont
         * @description A user-uploaded font, embedded so the template stays self-contained (D18).
         */
        CustomFont: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "ttf" | "otf" | "woff" | "woff2";
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
        };
        /** Dots */
        Dots: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Radius
             * @default 5
             */
            radius: number;
        };
        /** Edge */
        Edge: {
            /**
             * Depth
             * @default 2
             */
            depth: number;
            /**
             * Style
             * @default reeded
             * @enum {string}
             */
            style: "plain" | "reeded";
            /**
             * Teeth
             * @default 120
             */
            teeth: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Loc */
            loc: (string | number)[];
            /** Msg */
            msg: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: components["schemas"]["ErrorDetail"][];
        };
        /** ExportBody */
        ExportBody: {
            config: components["schemas"]["CoinConfig"];
            /**
             * Format
             * @default stl
             * @enum {string}
             */
            format: "stl" | "3mf" | "3mf-prusa" | "stl-pair";
        };
        /** FaceConfig */
        FaceConfig: {
            bottom_text?: components["schemas"]["TextConfig"];
            dots?: components["schemas"]["Dots"];
            icon?: components["schemas"]["IconPlacement"] | null;
            inlay?: components["schemas"]["ColorRef"];
            top_text?: components["schemas"]["TextConfig"];
        };
        /** Faces */
        Faces: {
            back?: components["schemas"]["FaceConfig"];
            front?: components["schemas"]["FaceConfig"];
        };
        /** FilamentDTO */
        FilamentDTO: {
            /** Finish */
            finish: string;
            /** Hex */
            hex: string;
            /**
             * Hex Source
             * @enum {string}
             */
            hex_source: "measured" | "override";
            /** Id */
            id: string;
            /** Material */
            material: string;
            /** Name */
            name: string;
            /** Source Url */
            source_url?: string | null;
            /** Vendor */
            vendor: string;
        };
        /** FilamentSwapDTO */
        FilamentSwapDTO: {
            /** Color */
            color: string;
            /**
             * Material
             * @enum {string}
             */
            material: "body" | "enamel_front" | "enamel_back";
            /** Z Mm */
            z_mm: number;
        };
        /** FilamentVersionDTO */
        FilamentVersionDTO: {
            /** Db Last Modified */
            db_last_modified: number | null;
            /** Db Version */
            db_version: number | null;
            /** Etag */
            etag?: string | null;
            /** Refreshed At */
            refreshed_at: string | null;
        };
        /** FontDTO */
        FontDTO: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Single Story A */
            single_story_a: boolean;
            /** Woff2 Url */
            woff2_url: string;
        };
        /** FontInspectResponse */
        FontInspectResponse: {
            /** Family */
            family: string;
            /** Format */
            format: string;
            /** Glyph Count */
            glyph_count: number;
            /** Name */
            name: string;
            /** Sample Svg */
            sample_svg: string;
            /** Sha256 */
            sha256: string;
            /** Style */
            style: string;
            /** Warnings */
            warnings: string[];
        };
        /**
         * FontRef
         * @description Either a built-in font by ``key`` or an embedded ``custom`` font.
         */
        FontRef: {
            custom?: components["schemas"]["CustomFont"] | null;
            /** Key */
            key?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Cache */
            cache: {
                [key: string]: number;
            };
            /** Environment */
            environment: string;
            /** Filaments */
            filaments: number;
            /** Fonts */
            fonts: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * IconGeometry
         * @description Traced outline: max radius 100, centred on the origin, Y up.
         */
        IconGeometry: {
            /** Polygons */
            polygons: components["schemas"]["IconPolygon"][];
            source?: components["schemas"]["IconSource"] | null;
        };
        /** IconPlacement */
        IconPlacement: {
            /**
             * Dx
             * @default 0
             */
            dx: number;
            /**
             * Dy
             * @default 0
             */
            dy: number;
            /**
             * Fit
             * @default 0.82
             */
            fit: number;
            geometry: components["schemas"]["IconGeometry"];
            /**
             * Rot
             * @default 0
             */
            rot: number;
        };
        /** IconPolygon */
        IconPolygon: {
            /** Exterior */
            exterior: [
                number,
                number
            ][];
            /** Holes */
            holes?: [
                number,
                number
            ][][];
        };
        /**
         * IconSource
         * @description Provenance of a traced icon. Optional and not hashed.
         */
        IconSource: {
            /** Data Url */
            data_url?: string | null;
            /** Filename */
            filename?: string | null;
            /** Sha256 */
            sha256?: string | null;
            trace?: components["schemas"]["TraceOptions"] | null;
        };
        /** MaterialStatsDTO */
        MaterialStatsDTO: {
            /** Color */
            color: string;
            /** Grams */
            grams: number;
            /**
             * Material
             * @enum {string}
             */
            material: "body" | "enamel_front" | "enamel_back";
            /** Volume Mm3 */
            volume_mm3: number;
        };
        /**
         * Meta
         * @description Free-form, excluded from hashing.
         */
        Meta: {
            /**
             * Created With
             * @default
             */
            created_with: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        } & {
            [key: string]: unknown;
        };
        /** PresetDTO */
        PresetDTO: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Patch */
            patch: {
                [key: string]: unknown;
            };
        };
        /** PreviewGlbBody */
        PreviewGlbBody: {
            config: components["schemas"]["CoinConfig"];
            /**
             * Quality
             * @default preview
             * @enum {string}
             */
            quality: "preview" | "export";
        };
        /** PreviewSvgBody */
        PreviewSvgBody: {
            config: components["schemas"]["CoinConfig"];
            /**
             * Face
             * @default front
             * @enum {string}
             */
            face: "front" | "back";
            /**
             * Quality
             * @default export
             * @enum {string}
             */
            quality: "preview" | "export";
        };
        /** PrintSettings */
        PrintSettings: {
            /**
             * Enamel Depth Mm
             * @default 0.4
             */
            enamel_depth_mm: number;
            /**
             * Nozzle Mm
             * @default 0.4
             */
            nozzle_mm: number;
        };
        /** Rings */
        Rings: {
            /**
             * Divider
             * @default true
             */
            divider: boolean;
            /**
             * R Div In
             * @default 101
             */
            r_div_in: number;
            /**
             * R Div Out
             * @default 113
             */
            r_div_out: number;
            /**
             * R Edge
             * @default 160
             */
            r_edge: number;
            /**
             * R Inlay
             * @default 143
             */
            r_inlay: number;
            /**
             * R Rim
             * @default 151
             */
            r_rim: number;
        };
        /** Size */
        Size: {
            /**
             * Body Mm
             * @default 2.5
             */
            body_mm: number;
            /**
             * Diameter Mm
             * @default 50
             */
            diameter_mm: number;
            /**
             * Relief Mm
             * @default 0.7
             */
            relief_mm: number;
        };
        /**
         * StatsResponse
         * @description Print summary. Grams assume PLA (1.24 g/cm³) at 100 % infill.
         */
        StatsResponse: {
            /** Diameter Mm */
            diameter_mm: number;
            /** Grams */
            grams: number;
            /** Materials */
            materials: components["schemas"]["MaterialStatsDTO"][];
            /** Swaps */
            swaps: components["schemas"]["FilamentSwapDTO"][];
            /** Thickness Mm */
            thickness_mm: number;
        };
        /** TemplateDTO */
        TemplateDTO: {
            config: components["schemas"]["CoinConfig"];
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Thumbnail Svg */
            thumbnail_svg: string;
        };
        /** TextConfig */
        TextConfig: {
            /**
             * Letter Spacing
             * @default 1.2
             */
            letter_spacing: number;
            /** Radius */
            radius: number;
            /**
             * Size
             * @default 26
             */
            size: number;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** TraceOptions */
        TraceOptions: {
            /**
             * Drop Largest
             * @default false
             */
            drop_largest: boolean;
            /**
             * Drop Thin Rings
             * @default true
             */
            drop_thin_rings: boolean;
            /** Inner Disc */
            inner_disc?: number | null;
            /**
             * Invert
             * @default false
             */
            invert: boolean;
            /**
             * Min Area
             * @default 0
             */
            min_area: number;
            /**
             * Simplify
             * @default 0.4
             */
            simplify: number;
            /**
             * Threshold
             * @default 128
             */
            threshold: number;
        };
        /** TraceResponse */
        TraceResponse: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            geometry: components["schemas"]["IconGeometry"];
            /** Holes */
            holes: number;
            /** Parts */
            parts: number;
            /** Preview Svg */
            preview_svg: string;
            /** Warnings */
            warnings: string[];
        };
        /** ValidateResponse */
        ValidateResponse: {
            config: components["schemas"]["CoinConfig"];
            /** Ok */
            ok: boolean;
            /** Warnings */
            warnings: components["schemas"]["WarningDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningDTO */
        WarningDTO: {
            /** Code */
            code: string;
            /** Msg */
            msg: string;
            /** Path */
            path: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "error";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    contact_api_contact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    filaments_api_filaments_get: {
        parameters: {
            query?: {
                q?: string | null;
                vendor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilamentDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filaments_version_api_filaments_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilamentVersionDTO"];
                };
            };
        };
    };
    fonts_api_fonts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontDTO"][];
                };
            };
        };
    };
    inspect_font_api_fonts_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_inspect_font_api_fonts_inspect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontInspectResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    font_file_api_fonts__key__woff2_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    healthz_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    trace_api_icons_trace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_trace_api_icons_trace_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetDTO"][];
                };
            };
        };
    };
    preview_glb_api_preview_glb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewGlbBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": unknown;
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_svg_api_preview_svg_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewSvgBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    coin_config_schema_api_schema_coin_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stats_api_stats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDTO"][];
                };
            };
        };
    };
    validate_api_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
